name: 'elt_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'elt_lakehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  elt_lakehouse:
    staging:
      +database: lakehouse
      +schema: staging
      +materialized: table
    marts:
      +database: pg
      +schema: mart
      +materialized: table
