version: 2

sources:
  - name: github_data
    schema: main
    tables:
      - name: pull_requests
        meta:
          external_location: "s3://lakehouse/raw/github_data/pull_requests/*.parquet"
      - name: issues
        meta:
          external_location: "s3://lakehouse/raw/github_data/issues/*.parquet"
      - name: issues__labels
        meta:
          external_location: "s3://lakehouse/raw/github_data/issues__labels/*.parquet"
models:
  - name: stg_pull_requests
    description: "Staging model for pull requests."
    columns:
      - name: pr_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: pr_number
      - name: title
      - name: state
      - name: user_id

  - name: stg_issues
    description: "Staging model for issues."
    columns:
      - name: issue_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: issue_number
      - name: title
      - name: state
      - name: user_id

  - name: stg_users
    description: "Staging model for users extracted from PRs and Issues."
    columns:
      - name: user_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: user_login
